variables:
  BUILDER_IMAGE: ""

image: $BUILDER_IMAGE

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - "**/node_modules/"
  policy: pull

stages:
  - dependencies
  - lint
  - build

dependencies:
  stage: dependencies
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
      changes:
        - package-lock.json
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - package-lock.json
    - if: '$CI_COMMIT_TAG'
      changes:
        - package-lock.json
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
      - "**/node_modules/"
    policy: pull-push
  script:
    - npm install

### Staging build ###
.build_job:
  stage: build
  only:
    - master
  script:
    - npm run publish

lint:
  stage: lint
  script:
    - npm run lint
